[package]
name = "webapps"
version = "0.5.4"
edition = "2021"
description = "Web applications at your fingertips"
authors = ["cosmic-utils"]
license = "GPL-3.0-only"
repository = "https://github.com/cosmic-utils/web-apps.git"

[[bin]]
path = "src/main.rs"
name = "quick-webapps"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3.18", default-features = false, features = [
  "std",
  "fmt",
  "env-filter",
] }
tokio = { version = "1.4", features = ["full"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.5"
url = "2.5"
walkdir = "2.5"
dirs = "5.0"
once_cell = "1.20"
image = "0.25"
usvg = "0.44"
lazy_static = "1.5"
rust-embed = "8.5"
i18n-embed-fl = "0.9"
bytes = "1.9"
svg = "0.18"
base64 = "0.22"
ashpd = { version = "0.10.2", features = ["wayland"] }
strum = "0.26"
strum_macros = "0.26"
freedesktop-desktop-entry = "0.7"

[dependencies.i18n-embed]
version = "0.15"
features = ["fluent-system", "desktop-requester"]

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["tokio", "winit", "wgpu"]

# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }

[package.metadata.deb]
license-file = "LICENSE"
assets = [
  [
    "target/release/quick-webapps",
    "usr/bin/",
    "755",
  ],
  [
    "res/io.github.elevenhsoft.WebApps.desktop",
    "usr/share/applications/",
    "644",
  ],
  [
    "res/io.github.elevenhsoft.WebApps.metainfo.xml",
    "usr/share/metainfo/",
    "644",
  ],
  [
    "res/icons/hicolor/**/*",
    "usr/share/icons/hicolor/",
    "644",
  ],
]

[package.metadata.generate-rpm]
assets = [
  { source = "target/release/quick-webapps", dest = "/usr/bin/", mode = "755" },
  { source = "LICENSE", dest = "/usr/share/doc/wizard/LICENSE", doc = true, mode = "644" },
  { source = "res/*.desktop", dest = "/usr/share/applications/", mode = "644" },
  { source = "res/icons/hicolor/**/*", dest = "/usr/share/icons/hicolor/", mode = "644" },
]

[package.metadata.aur]
files = [
  [
    "res/io.github.elevenhsoft.WebApps.desktop",
    "/usr/share/applications/io.github.elevenhsoft.WebApps.desktop",
  ],
  [
    "res/io.github.elevenhsoft.WebApps.metainfo.xml",
    "/usr/share/metainfo/io.github.elevenhsoft.WebApps.metainfo.xml",
  ],
  [
    "LICENSE",
    "/usr/share/doc/quick-webapps/LICENSE",
  ],
  [
    "res/icons/hicolor/16x16/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/16x16/apps/io.github.elevenhsoft.WebApps.png",
  ],
  [
    "res/icons/hicolor/24x24/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/24x24/apps/io.github.elevenhsoft.WebApps.png",
  ],
  [
    "res/icons/hicolor/32x32/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/32x32/apps/io.github.elevenhsoft.WebApps.png",
  ],
  [
    "res/icons/hicolor/48x48/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/48x48/apps/io.github.elevenhsoft.WebApps.png",
  ],
  [
    "res/icons/hicolor/64x64/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/64x64/apps/io.github.elevenhsoft.WebApps.png",
  ],
  [
    "res/icons/hicolor/128x128/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/128x128/apps/io.github.elevenhsoft.WebApps.png",
  ],
  [
    "res/icons/hicolor/256x256/apps/io.github.elevenhsoft.WebApps.png",
    "/usr/share/icons/hicolor/256x256/apps/io.github.elevenhsoft.WebApps.png",
  ],
]
